// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// agca_row_norms_cpp
arma::vec agca_row_norms_cpp(const arma::mat& x);
RcppExport SEXP _AGCA4extremes_agca_row_norms_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_row_norms_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// agca_normalize_rows_cpp
arma::mat agca_normalize_rows_cpp(arma::mat x);
RcppExport SEXP _AGCA4extremes_agca_normalize_rows_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_normalize_rows_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// agca_departures_cpp
Rcpp::List agca_departures_cpp(arma::mat g, arma::vec mu, bool normalize);
RcppExport SEXP _AGCA4extremes_agca_departures_cpp(SEXP gSEXP, SEXP muSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_departures_cpp(g, mu, normalize));
    return rcpp_result_gen;
END_RCPP
}
// agca_core_cpp
Rcpp::List agca_core_cpp(arma::mat g, arma::vec mu, bool normalize);
RcppExport SEXP _AGCA4extremes_agca_core_cpp(SEXP gSEXP, SEXP muSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_core_cpp(g, mu, normalize));
    return rcpp_result_gen;
END_RCPP
}
// agca_reconstruct_cpp
arma::mat agca_reconstruct_cpp(const arma::vec& anchor_coordinate, const arma::vec& mu, const arma::mat& scores, const arma::mat& loadings, int p);
RcppExport SEXP _AGCA4extremes_agca_reconstruct_cpp(SEXP anchor_coordinateSEXP, SEXP muSEXP, SEXP scoresSEXP, SEXP loadingsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type anchor_coordinate(anchor_coordinateSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type loadings(loadingsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_reconstruct_cpp(anchor_coordinate, mu, scores, loadings, p));
    return rcpp_result_gen;
END_RCPP
}
// agca_residual_risk_cpp
arma::vec agca_residual_risk_cpp(const arma::mat& u, const arma::mat& scores, const arma::mat& loadings, int max_rank);
RcppExport SEXP _AGCA4extremes_agca_residual_risk_cpp(SEXP uSEXP, SEXP scoresSEXP, SEXP loadingsSEXP, SEXP max_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type loadings(loadingsSEXP);
    Rcpp::traits::input_parameter< int >::type max_rank(max_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_residual_risk_cpp(u, scores, loadings, max_rank));
    return rcpp_result_gen;
END_RCPP
}
// agca_geodesic_distance_cpp
arma::vec agca_geodesic_distance_cpp(arma::mat x, arma::mat y, bool normalize);
RcppExport SEXP _AGCA4extremes_agca_geodesic_distance_cpp(SEXP xSEXP, SEXP ySEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(agca_geodesic_distance_cpp(x, y, normalize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AGCA4extremes_agca_row_norms_cpp", (DL_FUNC) &_AGCA4extremes_agca_row_norms_cpp, 1},
    {"_AGCA4extremes_agca_normalize_rows_cpp", (DL_FUNC) &_AGCA4extremes_agca_normalize_rows_cpp, 1},
    {"_AGCA4extremes_agca_departures_cpp", (DL_FUNC) &_AGCA4extremes_agca_departures_cpp, 3},
    {"_AGCA4extremes_agca_core_cpp", (DL_FUNC) &_AGCA4extremes_agca_core_cpp, 3},
    {"_AGCA4extremes_agca_reconstruct_cpp", (DL_FUNC) &_AGCA4extremes_agca_reconstruct_cpp, 5},
    {"_AGCA4extremes_agca_residual_risk_cpp", (DL_FUNC) &_AGCA4extremes_agca_residual_risk_cpp, 4},
    {"_AGCA4extremes_agca_geodesic_distance_cpp", (DL_FUNC) &_AGCA4extremes_agca_geodesic_distance_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_AGCA4extremes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
