# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

agca_row_norms_cpp <- function(x) {
    .Call(`_AGCA4extremes_agca_row_norms_cpp`, x)
}

agca_normalize_rows_cpp <- function(x) {
    .Call(`_AGCA4extremes_agca_normalize_rows_cpp`, x)
}

agca_departures_cpp <- function(g, mu, normalize = TRUE) {
    .Call(`_AGCA4extremes_agca_departures_cpp`, g, mu, normalize)
}

agca_core_cpp <- function(g, mu, normalize = TRUE) {
    .Call(`_AGCA4extremes_agca_core_cpp`, g, mu, normalize)
}

agca_reconstruct_cpp <- function(anchor_coordinate, mu, scores, loadings, p) {
    .Call(`_AGCA4extremes_agca_reconstruct_cpp`, anchor_coordinate, mu, scores, loadings, p)
}

agca_residual_risk_cpp <- function(u, scores, loadings, max_rank) {
    .Call(`_AGCA4extremes_agca_residual_risk_cpp`, u, scores, loadings, max_rank)
}

agca_geodesic_distance_cpp <- function(x, y, normalize = TRUE) {
    .Call(`_AGCA4extremes_agca_geodesic_distance_cpp`, x, y, normalize)
}

